title: A quick guide to Earth
description: Learn all there is to know about interacting with earthlings!
theme: just-the-docs

url: https://ScottGreenhorn.github.io
baseurl: /Hit-the-Mark-docs

aux_links:
  Help Repository: https://github.com/ScottGreenhorn/Hit-the-Mark-doc

# Note and tip styles
callouts:
  note:
    color: green
    title: Note    
  caution:
    color: red
    title: Caution

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Something missing or something wrong? Edit this page"
gh_edit_repository: "https://github.com/ScottGreenhorn/Hit-the-Mark-doc" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "edit" # "tree" or "edit" if you want the user to jump into the editor immediately
