title: A quick guide to Earth
description: Learn all there is to know about interacting with earthlings!
theme: just-the-docs

url: https://ScottGreenhorn.github.io
baseurl: /Hit-the-Mark-docs

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
