title: A quick guide to Earth
description: Learn all there is to know about interacting with earthlings!
theme: just-the-docs

url: https://ScottGreenhorn.github.io
baseurl: /Hit-the-Mark-docs

aux_links:
  Help Repository: https://github.com/ScottGreenhorn/Hit-the-Mark-doc
